"""Reporting, export, workflow, and performance helpers."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from jinja2 import Template

from ._compat import r_aliases
from ._utils import ensure_dataframe


def export_gazepoint_tables(
    tables, output_dir, prefix="gazepoint", index=False, **kwargs
) -> dict[str, str]:
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    out = {}
    items = tables.items() if isinstance(tables, dict) else [("table", tables)]
    for name, obj in items:
        if isinstance(obj, pd.DataFrame):
            path = root / f"{prefix}_{name}.csv"
            obj.to_csv(path, index=index)
            out[name] = str(path)
    return out


def export_gazepoint_model_tables(models, output_dir, prefix="model", **kwargs):
    from .stats import tidy_gazepoint_model_summary

    models = models if isinstance(models, dict) else {"model": models}
    tables = {name: tidy_gazepoint_model_summary(model) for name, model in models.items()}
    return export_gazepoint_tables(tables, output_dir, prefix=prefix, **kwargs)


def write_gazepoint_outputs(results, output_dir, prefix="gazepoint", **kwargs):
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    written = {}
    if isinstance(results, pd.DataFrame):
        results = {"result": results}
    if isinstance(results, dict):
        for k, v in results.items():
            if isinstance(v, pd.DataFrame):
                p = root / f"{prefix}_{k}.csv"
                v.to_csv(p, index=False)
                written[k] = str(p)
            elif isinstance(v, (dict, list, tuple, str, int, float, bool)):
                try:
                    p = root / f"{prefix}_{k}.json"
                    p.write_text(json.dumps(v, indent=2, default=str), encoding="utf-8")
                    written[k] = str(p)
                except Exception:
                    pass
    return written


def export_gazepoint_master_audit(data, output_dir=".", prefix="master_audit", **kwargs):
    """Export the current Python master audit; output_dir now matches R optionality."""
    from .qc import audit_gazepoint_master

    return export_gazepoint_tables(audit_gazepoint_master(data), output_dir, prefix=prefix)


def save_gazepoint_plots(plots, output_dir, prefix="plot", dpi=150, **kwargs):
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    out = {}
    plots = plots if isinstance(plots, dict) else {"plot": plots}
    for name, fig in plots.items():
        if hasattr(fig, "savefig"):
            p = root / f"{prefix}_{name}.png"
            fig.savefig(p, dpi=dpi, bbox_inches="tight")
            out[name] = str(p)
    return out


def create_gazepoint_reporting_checklist(data=None) -> pd.DataFrame:
    items = [
        "hardware and sampling rate",
        "calibration procedure",
        "tracking-quality criteria",
        "missing-data handling",
        "pupil preprocessing",
        "AOI definitions",
        "event detector",
        "exclusion criteria",
        "statistical model",
        "software/version",
        "sensitivity analyses",
        "open materials/data",
    ]
    return pd.DataFrame({"item": items, "reported": [False] * len(items)})


def create_gazepoint_analysis_decision_audit(**decisions) -> pd.DataFrame:
    return (
        pd.DataFrame([{"decision": k, "value": str(v)} for k, v in decisions.items()])
        if decisions
        else pd.DataFrame(columns=["decision", "value"])
    )


def _html_table(obj):
    return (
        obj.to_html(index=False, border=0)
        if isinstance(obj, pd.DataFrame)
        else f"<pre>{json.dumps(obj, indent=2, default=str)}</pre>"
    )


def create_gazepoint_report(
    results,
    output_file="gazepoint_report.html",
    title="gp3tools analysis report",
    metadata=None,
    **kwargs,
) -> Path:
    sections = []
    if isinstance(results, pd.DataFrame):
        results = {"Results": results}
    for name, obj in results.items() if isinstance(results, dict) else [("Results", results)]:
        sections.append((str(name).replace("_", " ").title(), _html_table(obj)))
    tpl = Template(
        """<!doctype html><html><head><meta charset="utf-8"><title>{{ title }}</title><style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;line-height:1.45}table{border-collapse:collapse;width:100%;font-size:.9rem}th,td{border-bottom:1px solid #ddd;padding:.35rem;text-align:left}code,pre{background:#f5f5f5;padding:.4rem;overflow:auto}</style></head><body><h1>{{ title }}</h1><p>Generated by gp3tools for Python.</p>{% if metadata %}<h2>Metadata</h2><pre>{{ metadata }}</pre>{% endif %}{% for h,b in sections %}<h2>{{ h }}</h2>{{ b|safe }}{% endfor %}</body></html>"""
    )
    p = Path(output_file)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        tpl.render(
            title=title,
            sections=sections,
            metadata=json.dumps(metadata or {}, indent=2, default=str),
        ),
        encoding="utf-8",
    )
    return p


def report_gazepoint_missingness(
    data,
    cols=None,
    group_cols=None,
    digits=None,
    max_variables=None,
):
    """Return legacy text or the R v2.3.0 structured missingness report."""
    if cols is None and group_cols is None and digits is None and max_variables is None:
        from .qc import summarise_gazepoint_missingness

        summary = summarise_gazepoint_missingness(data)
        if summary.empty:
            return "No missingness summary available."
        column_name = "column" if "column" in summary else "variable"
        rate_name = "missing_prop" if "missing_prop" in summary else "missing_rate"
        top = summary.sort_values(rate_name, ascending=False).iloc[0]
        return f"Highest missingness: {top[column_name]} ({top[rate_name]:.1%})."

    from .qc import summarise_gazepoint_missingness

    digits = 1 if digits is None else int(digits)
    max_variables = 5 if max_variables is None else int(max_variables)
    if digits < 0 or max_variables < 1:
        raise ValueError("digits must be non-negative and max_variables positive")
    if isinstance(data, pd.DataFrame) and {
        "group_id",
        "variable",
        "n_rows",
        "n_missing",
        "missing_rate",
    }.issubset(data.columns):
        summary = data.copy()
    else:
        summary = summarise_gazepoint_missingness(data, cols=cols, group_cols=group_cols)
    variable_summary = (
        summary.groupby("variable", dropna=False, sort=False)[["n_rows", "n_missing"]]
        .sum()
        .reset_index()
    )
    variable_summary["missing_rate"] = np.where(
        variable_summary["n_rows"] > 0,
        variable_summary["n_missing"] / variable_summary["n_rows"],
        np.nan,
    )
    variable_summary = variable_summary.sort_values("missing_rate", ascending=False)
    total_rows = float(variable_summary["n_rows"].sum())
    total_missing = float(variable_summary["n_missing"].sum())
    overall_rate = total_missing / total_rows if total_rows > 0 else np.nan
    top = variable_summary.head(max_variables)
    top_text = (
        ", ".join(
            f"{row.variable} ({round(100 * row.missing_rate, digits)}%)"
            for row in top.itertuples(index=False)
        )
        or "no variables"
    )
    text = (
        f"Missingness was summarized across {summary['variable'].nunique()} variable(s). "
        f"The overall cell-level missingness rate was {round(100 * overall_rate, digits)}%. "
        f"The highest missingness variable(s) were: {top_text}. These values are descriptive "
        "data-coverage diagnostics and do not by themselves define exclusion decisions."
    )
    overall = pd.DataFrame(
        [
            {
                "n_variables": int(summary["variable"].nunique()),
                "n_groups": int(summary["group_id"].nunique()),
                "total_cells": total_rows,
                "total_missing": total_missing,
                "overall_missing_rate": overall_rate,
            }
        ]
    )
    return {
        "summary": summary,
        "overall": overall,
        "variable_summary": variable_summary,
        "report_text": text,
    }


def report_gazepoint_phase_coverage(
    data,
    phase_col="task_phase",
    group_cols=None,
    time_col=None,
    value_cols=None,
    digits=None,
):
    """Return legacy text or the R v2.3.0 structured phase-coverage report."""
    if group_cols is None and time_col is None and value_cols is None and digits is None:
        df = ensure_dataframe(data, copy=False)
        if phase_col not in df:
            return "No task-phase column available."
        counts = df[phase_col].value_counts(dropna=False)
        return f"Task-phase coverage: {len(counts)} phase(s) across {len(df)} row(s)."

    from .qc import summarise_gazepoint_phase_coverage

    digits = 1 if digits is None else int(digits)
    if digits < 0:
        raise ValueError("digits must be non-negative")
    required_summary = {"group_id", "phase", "n_rows"}
    summary = (
        data.copy()
        if isinstance(data, pd.DataFrame) and required_summary.issubset(data.columns)
        else summarise_gazepoint_phase_coverage(
            data,
            phase_col=phase_col,
            group_cols=group_cols,
            time_col=time_col,
            value_cols=value_cols,
        )
    )
    phase_totals = (
        summary.groupby("phase", dropna=False, sort=False)["n_rows"]
        .sum()
        .reset_index()
        .sort_values("n_rows", ascending=False)
    )
    total_rows = int(phase_totals["n_rows"].sum())
    n_phases = int(summary["phase"].nunique(dropna=False))
    n_groups = int(summary["group_id"].nunique(dropna=False))
    least = phase_totals.sort_values("n_rows", ascending=True).iloc[0]
    if "complete_value_rate" in summary:
        rates = pd.to_numeric(summary["complete_value_rate"], errors="coerce")
        weights = pd.to_numeric(summary["n_rows"], errors="coerce")
        valid = rates.notna() & weights.notna()
        weighted_complete = (
            float(np.average(rates[valid], weights=weights[valid])) if valid.any() else np.nan
        )
    else:
        weighted_complete = np.nan
    complete_text = (
        f" The weighted complete-value rate across summarized phases was "
        f"{round(100 * weighted_complete, digits)}%."
        if np.isfinite(weighted_complete)
        else ""
    )
    report_text = (
        f"Task-phase coverage was summarized across {n_phases} phase(s) and {n_groups} "
        f"group(s), representing {total_rows} row(s). The least represented phase was "
        f"'{least['phase']}' with {int(least['n_rows'])} row(s).{complete_text} "
        "These values are descriptive data-coverage diagnostics and do not by themselves "
        "define exclusion decisions."
    )
    overall = pd.DataFrame(
        [
            {
                "n_phases": n_phases,
                "n_groups": n_groups,
                "total_rows": total_rows,
                "least_represented_phase": least["phase"],
                "least_represented_phase_rows": int(least["n_rows"]),
                "weighted_complete_value_rate": weighted_complete,
            }
        ]
    )
    return {
        "summary": summary,
        "overall": overall,
        "phase_totals": phase_totals,
        "report_text": report_text,
    }


def report_gazepoint_qc_overview(data, max_objects=None):
    """Return the legacy short text or an R-style structured QC overview."""
    from .qc import summarise_gazepoint_qc_status

    if isinstance(data, pd.DataFrame) and {"object_name", "qc_status"}.issubset(data.columns):
        summary_table = data[["object_name", "qc_status"]].copy()
    elif isinstance(data, pd.DataFrame) and {"component", "status"}.issubset(data.columns):
        summary_table = data[["component", "status"]].copy()
    else:
        summary_table = summarise_gazepoint_qc_status(data)
    if max_objects is None:
        return f"QC summary contains {len(summary_table)} evaluated unit(s)."
    try:
        max_objects = int(max_objects)
    except (TypeError, ValueError) as exc:
        raise ValueError("max_objects must be a positive integer") from exc
    if max_objects < 1:
        raise ValueError("max_objects must be a positive integer")

    if {"component", "status"}.issubset(summary_table.columns):
        object_summary = summary_table.rename(
            columns={"component": "object_name", "status": "qc_status"}
        ).copy()
    else:
        object_summary = summary_table.copy()
        if "object_name" not in object_summary:
            object_summary["object_name"] = [f"object_{i + 1}" for i in range(len(object_summary))]
        if "qc_status" not in object_summary:
            object_summary["qc_status"] = "unknown"
    status = object_summary["qc_status"].astype(str)
    counts = {
        label: int(status.eq(label).sum()) for label in ["pass", "warn", "fail", "info", "unknown"]
    }
    counts["unknown"] += int(
        ~status.isin(
            ["pass", "warn", "fail", "info", "unknown", "available", "not_available"]
        ).sum()
    )
    counts["pass"] += int(status.eq("available").sum())
    counts["unknown"] += int(status.eq("not_available").sum())
    overall_status = (
        "fail" if counts["fail"] else "warn" if counts["warn"] or counts["unknown"] else "pass"
    )
    overview = pd.DataFrame(
        [
            {
                "n_objects": len(object_summary),
                "n_pass": counts["pass"],
                "n_warn": counts["warn"],
                "n_fail": counts["fail"],
                "n_info": counts["info"],
                "n_unknown": counts["unknown"],
                "qc_overview_status": overall_status,
            }
        ]
    )
    review = object_summary.loc[
        object_summary["qc_status"].astype(str).isin(["fail", "warn", "unknown", "not_available"])
    ].copy()
    priority = {"fail": 0, "warn": 1, "unknown": 2, "not_available": 2}
    if len(review):
        review["_order"] = review["qc_status"].astype(str).map(priority).fillna(3)
        review = review.sort_values(["_order", "object_name"], kind="stable")
    names = review["object_name"].head(max_objects).astype(str).tolist() if len(review) else []
    review_text = ", ".join(names) if names else "none"
    report_text = (
        f"QC overview collected {len(object_summary)} object(s): "
        f"{counts['pass']} pass, {counts['warn']} warn, {counts['fail']} fail, "
        f"{counts['info']} info, and {counts['unknown']} unknown. "
        f"Overall QC overview status was '{overall_status}'. "
        f"Object(s) needing review or interpretation: {review_text}. "
        "This overview is a reporting aid only; it does not replace the underlying "
        "audit outputs, readiness gates, or exclusion decisions."
    )
    return {
        "summary": {"overview": overview, "object_summary": object_summary},
        "object_summary": object_summary,
        "report_text": report_text,
        "_gp3_class": "gp3_qc_overview_report",
    }


def report_gazepoint_face_qc(data) -> str:
    from .face import audit_gazepoint_face_quality

    q = audit_gazepoint_face_quality(data)
    return f"Face-quality audit evaluated {int(q['n'].iloc[0])} row(s)."


def report_gazepoint_multiverse(
    data,
    *,
    branch_col=None,
    term_col=None,
    estimate_col=None,
    p_col=None,
    status_col=None,
    alpha=None,
):
    """Report multiverse results; bare DataFrame input retains the historical string."""
    if all(
        value is None for value in (branch_col, term_col, estimate_col, p_col, status_col, alpha)
    ):
        from .stats import summarise_gazepoint_multiverse_results

        summary = summarise_gazepoint_multiverse_results(data)
        if isinstance(summary, pd.DataFrame):
            return (
                f"Multiverse contained {int(summary['n_specifications'].iloc[0])} specification(s)."
            )

    alpha = 0.05 if alpha is None else float(alpha)
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    if isinstance(data, dict):
        frame = data.get("branch_summary")
        if frame is None:
            frame = data.get("branch_results")
    else:
        frame = data
    frame = ensure_dataframe(frame, copy=False)

    def first(supplied, candidates):
        if supplied is not None:
            if supplied not in frame.columns:
                raise ValueError(f"{supplied} was not found")
            return supplied
        return next((candidate for candidate in candidates if candidate in frame.columns), None)

    branch_col = first(branch_col, ["branch", "specification", "model", "analysis", ".gp3_branch"])
    term_col = first(term_col, ["term", "parameter", "effect", "coefficient"])
    estimate_col = first(estimate_col, ["estimate", "effect_size", "beta", "b"])
    p_col = first(p_col, ["p.value", "p_value", "p", "Pr(>|z|)", "Pr(>|t|)"])
    status_col = first(status_col, ["status", "model_status", "fit_status", "branch_status"])
    work = frame.copy()
    if branch_col is None:
        work[".gp3_branch"] = "all"
        branch_col = ".gp3_branch"
    if status_col is None:
        work[".gp3_status"] = "unknown"
        status_col = ".gp3_status"

    branch_summary = (
        work.groupby(branch_col, sort=True, dropna=True)
        .agg(
            n_rows=(branch_col, "size"),
            status=(status_col, lambda values: ";".join(sorted(set(map(str, values))))),
        )
        .reset_index()
        .rename(columns={branch_col: "branch"})
    )
    if term_col is not None:
        n_terms = work.groupby(branch_col, sort=True)[term_col].nunique()
        branch_summary["n_terms"] = branch_summary["branch"].map(n_terms)
    else:
        branch_summary["n_terms"] = np.nan
    status_summary = (
        work[status_col]
        .astype(str)
        .value_counts(sort=False)
        .rename_axis("status")
        .rename("n")
        .reset_index()
    )
    status_summary["prop"] = status_summary["n"] / status_summary["n"].sum()
    inferential = pd.DataFrame()
    if estimate_col is not None and p_col is not None:
        inferential = work[
            [branch_col] + ([term_col] if term_col else []) + [estimate_col, p_col]
        ].copy()
        inferential["significant"] = pd.to_numeric(inferential[p_col], errors="coerce") < alpha
    return {
        "branch_summary": branch_summary,
        "status_summary": status_summary,
        "inferential_summary": inferential,
        "alpha": alpha,
        "_gp3_class": "gp3_multiverse_report",
    }


def benchmark_gazepoint_export_performance(data, repeats=3, **kwargs) -> pd.DataFrame:
    from tempfile import TemporaryDirectory

    df = ensure_dataframe(data)
    rows = []
    with TemporaryDirectory() as d:
        for r in range(repeats):
            p = Path(d) / f"bench_{r}.csv"
            start = time.perf_counter()
            df.to_csv(p, index=False)
            elapsed = time.perf_counter() - start
            rows.append(
                {
                    "repeat": r + 1,
                    "n_rows": len(df),
                    "n_columns": df.shape[1],
                    "elapsed_seconds": elapsed,
                    "rows_per_second": len(df) / elapsed if elapsed else np.inf,
                    "bytes": p.stat().st_size,
                }
            )
    return pd.DataFrame(rows)


def _gp3_perf_summarise_trials(results) -> pd.DataFrame:
    df = ensure_dataframe(results, copy=False)

    if not len(df):
        return pd.DataFrame()

    required = {
        "scale_id",
        "total_rows",
        "n_files",
        "rows_per_file",
        "operation",
        "status",
        "elapsed_s",
        "heap_delta_mb",
        "output_size_mb",
    }

    missing = required - set(df.columns)

    if missing:
        raise ValueError("trial benchmark data is missing: " + ", ".join(sorted(missing)))

    group_cols = [
        "scale_id",
        "total_rows",
        "n_files",
        "rows_per_file",
        "operation",
    ]

    rows = []

    for keys, part in df.groupby(
        group_cols,
        dropna=False,
        sort=False,
    ):
        if not isinstance(keys, tuple):
            keys = (keys,)

        values = dict(zip(group_cols, keys, strict=True))
        ok = part["status"].astype("string").eq("ok")

        elapsed = pd.to_numeric(
            part.loc[ok, "elapsed_s"],
            errors="coerce",
        )

        heap = pd.to_numeric(
            part.loc[ok, "heap_delta_mb"],
            errors="coerce",
        )

        output = pd.to_numeric(
            part.loc[ok, "output_size_mb"],
            errors="coerce",
        )

        def median_or_nan(x):
            x = x[np.isfinite(x)]
            return float(x.median()) if len(x) else np.nan

        def min_or_nan(x):
            x = x[np.isfinite(x)]
            return float(x.min()) if len(x) else np.nan

        def max_or_nan(x):
            x = x[np.isfinite(x)]
            return float(x.max()) if len(x) else np.nan

        rows.append(
            {
                **values,
                "n_trials": int(len(part)),
                "n_success": int(ok.sum()),
                "median_elapsed_s": median_or_nan(elapsed),
                "minimum_elapsed_s": min_or_nan(elapsed),
                "maximum_elapsed_s": max_or_nan(elapsed),
                "median_heap_delta_mb": median_or_nan(heap),
                "maximum_heap_delta_mb": max_or_nan(heap),
                "median_output_size_mb": median_or_nan(output),
            }
        )

    out = pd.DataFrame(rows)

    return out.sort_values(
        [
            "operation",
            "total_rows",
            "n_files",
        ],
        kind="stable",
    ).reset_index(drop=True)


def _gp3_perf_as_summary(x) -> pd.DataFrame:
    if isinstance(x, dict):
        if "summary" not in x:
            raise TypeError("benchmark dictionary must contain a 'summary' table")

        return ensure_dataframe(
            x["summary"],
            copy=False,
        ).copy()

    df = ensure_dataframe(
        x,
        copy=False,
    )

    if {
        "trial",
        "elapsed_s",
        "status",
    }.issubset(df.columns):
        return _gp3_perf_summarise_trials(df)

    return df.copy()


def _gp3_perf_validate_limits(limits) -> pd.DataFrame:
    df = ensure_dataframe(
        limits,
        copy=False,
    )

    required = {
        "operation",
        "max_seconds_per_million_rows",
        "max_heap_delta_mb_per_million_rows",
        "max_scaling_exponent",
    }

    missing = required - set(df.columns)

    if missing:
        raise ValueError("limits is missing: " + ", ".join(sorted(missing)))

    return df.copy()


def _gp3_perf_positive_scalar(value, argument: str) -> float:
    try:
        value = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{argument} must be one positive finite number") from exc

    if not np.isfinite(value) or value <= 0:
        raise ValueError(f"{argument} must be one positive finite number")

    return value


def _gp3_perf_scaling_exponents(summary) -> pd.DataFrame:
    df = ensure_dataframe(
        summary,
        copy=False,
    )

    rows = []

    for operation in pd.unique(df["operation"]):
        part = df.loc[df["operation"].eq(operation)].copy()

        elapsed = pd.to_numeric(
            part["median_elapsed_s"],
            errors="coerce",
        )

        total_rows = pd.to_numeric(
            part["total_rows"],
            errors="coerce",
        )

        valid = np.isfinite(elapsed) & (elapsed > 0) & np.isfinite(total_rows) & (total_rows > 0)

        elapsed = elapsed[valid].to_numpy(float)
        total_rows = total_rows[valid].to_numpy(float)

        exponent = np.nan

        if len(np.unique(total_rows)) >= 2:
            exponent = float(
                np.polyfit(
                    np.log(total_rows),
                    np.log(elapsed),
                    1,
                )[0]
            )

        rows.append(
            {
                "operation": operation,
                "scaling_exponent": exponent,
            }
        )

    return pd.DataFrame(rows)


def _gp3_perf_check_rows(
    current,
    check: str,
    passed,
) -> pd.DataFrame:
    df = ensure_dataframe(
        current,
        copy=False,
    )

    passed = pd.Series(
        passed,
        index=df.index,
    ).fillna(False)

    return pd.DataFrame(
        {
            "operation": df["operation"].to_numpy(),
            "total_rows": df["total_rows"].to_numpy(),
            "n_files": df["n_files"].to_numpy(),
            "check": check,
            "status": np.where(
                passed.to_numpy(bool),
                "pass",
                "fail",
            ),
        }
    )


def gp3tools_performance_limits() -> pd.DataFrame:
    """Return the R gp3tools v2.3.0 performance thresholds."""
    return pd.DataFrame(
        {
            "operation": [
                "generate",
                "import",
                "master",
                "sampling",
                "quality",
            ],
            "max_seconds_per_million_rows": [
                90.0,
                240.0,
                240.0,
                180.0,
                180.0,
            ],
            "max_heap_delta_mb_per_million_rows": [
                1200.0,
                1800.0,
                1800.0,
                1200.0,
                1200.0,
            ],
            "max_scaling_exponent": [
                1.6,
                1.6,
                1.6,
                1.6,
                1.6,
            ],
        }
    )


def check_gazepoint_performance_regression(
    current=None,
    baseline=None,
    tolerance=0.20,
    metric="elapsed_seconds",
    *,
    x=None,
    limits=None,
    elapsed_ratio_limit=1.5,
    memory_ratio_limit=1.5,
):
    """Check performance regressions.

    ``x`` activates the R gp3tools v2.3.0 benchmark-regression
    interface. The historical Python ``current``/``baseline`` interface
    remains available for backward compatibility.

    A single positional R-style summary is also accepted when ``baseline``
    is omitted and the table has the R performance-summary columns.
    """
    if x is not None:
        if current is not None:
            raise TypeError("supply either current or x, not both")

        current = x
        r_mode = True
    else:
        r_required = {
            "operation",
            "total_rows",
            "n_files",
            "median_elapsed_s",
            "median_heap_delta_mb",
            "n_success",
            "n_trials",
        }

        r_mode = False

        if current is not None:
            try:
                candidate = _gp3_perf_as_summary(current)
                r_mode = r_required.issubset(candidate.columns)
            except Exception:
                r_mode = False

    if not r_mode:
        if current is None or baseline is None:
            raise TypeError("current and baseline are required for the legacy Python interface")

        current_df = ensure_dataframe(
            current,
            copy=False,
        )

        baseline_df = ensure_dataframe(
            baseline,
            copy=False,
        )

        if metric not in current_df:
            raise ValueError(f"current is missing metric {metric!r}")

        if metric not in baseline_df:
            raise ValueError(f"baseline is missing metric {metric!r}")

        c = float(
            pd.to_numeric(
                current_df[metric],
                errors="coerce",
            ).mean()
        )

        b = float(
            pd.to_numeric(
                baseline_df[metric],
                errors="coerce",
            ).mean()
        )

        change = (c - b) / b if b else np.nan

        return pd.DataFrame(
            {
                "current": [c],
                "baseline": [b],
                "relative_change": [change],
                "regression": [bool(np.isfinite(change) and change > tolerance)],
            }
        )

    if current is None:
        raise TypeError("x is required for the R-compatible interface")

    if limits is None:
        limits = gp3tools_performance_limits()

    limits = _gp3_perf_validate_limits(limits)

    elapsed_ratio_limit = _gp3_perf_positive_scalar(
        elapsed_ratio_limit,
        "elapsed_ratio_limit",
    )

    memory_ratio_limit = _gp3_perf_positive_scalar(
        memory_ratio_limit,
        "memory_ratio_limit",
    )

    evaluated = _gp3_perf_as_summary(current)

    required = {
        "operation",
        "total_rows",
        "n_files",
        "median_elapsed_s",
        "median_heap_delta_mb",
        "n_success",
        "n_trials",
    }

    missing = required - set(evaluated.columns)

    if missing:
        raise ValueError("x is missing required columns: " + ", ".join(sorted(missing)))

    evaluated = evaluated.copy()

    total_rows = pd.to_numeric(
        evaluated["total_rows"],
        errors="coerce",
    )

    elapsed = pd.to_numeric(
        evaluated["median_elapsed_s"],
        errors="coerce",
    )

    heap = pd.to_numeric(
        evaluated["median_heap_delta_mb"],
        errors="coerce",
    )

    denominator = np.maximum(
        total_rows.to_numpy(float) / 1_000_000.0,
        np.finfo(float).eps,
    )

    evaluated["seconds_per_million_rows"] = elapsed.to_numpy(float) / denominator

    evaluated["heap_mb_per_million_rows"] = heap.to_numpy(float) / denominator

    evaluated = evaluated.merge(
        limits,
        on="operation",
        how="left",
        sort=False,
    )

    scaling = _gp3_perf_scaling_exponents(evaluated)

    evaluated = evaluated.merge(
        scaling,
        on="operation",
        how="left",
        sort=False,
    )

    elapsed_limit = pd.to_numeric(
        evaluated["max_seconds_per_million_rows"],
        errors="coerce",
    )

    memory_limit = pd.to_numeric(
        evaluated["max_heap_delta_mb_per_million_rows"],
        errors="coerce",
    )

    scaling_limit = pd.to_numeric(
        evaluated["max_scaling_exponent"],
        errors="coerce",
    )

    scaling_value = pd.to_numeric(
        evaluated["scaling_exponent"],
        errors="coerce",
    )

    evaluated["elapsed_limit_pass"] = elapsed_limit.isna() | (
        evaluated["seconds_per_million_rows"] <= elapsed_limit
    )

    evaluated["memory_limit_pass"] = memory_limit.isna() | (
        evaluated["heap_mb_per_million_rows"] <= memory_limit
    )

    evaluated["scaling_limit_pass"] = (
        scaling_limit.isna() | scaling_value.isna() | (scaling_value <= scaling_limit)
    )

    evaluated["operation_success"] = pd.to_numeric(
        evaluated["n_success"],
        errors="coerce",
    ) == pd.to_numeric(
        evaluated["n_trials"],
        errors="coerce",
    )

    baseline_used = baseline is not None

    if baseline_used:
        baseline_summary = _gp3_perf_as_summary(baseline)

        baseline_keys = [
            "operation",
            "total_rows",
            "n_files",
        ]

        baseline_required = set(
            baseline_keys
            + [
                "median_elapsed_s",
                "median_heap_delta_mb",
            ]
        )

        baseline_missing = baseline_required - set(baseline_summary.columns)

        if baseline_missing:
            raise ValueError(
                "baseline is missing required columns: " + ", ".join(sorted(baseline_missing))
            )

        baseline_keep = baseline_summary[
            baseline_keys
            + [
                "median_elapsed_s",
                "median_heap_delta_mb",
            ]
        ].rename(
            columns={
                "median_elapsed_s": "baseline_elapsed_s",
                "median_heap_delta_mb": "baseline_heap_delta_mb",
            }
        )

        evaluated = evaluated.merge(
            baseline_keep,
            on=baseline_keys,
            how="left",
            sort=False,
        )

        evaluated["elapsed_ratio"] = evaluated["median_elapsed_s"] / evaluated["baseline_elapsed_s"]

        evaluated["memory_ratio"] = (
            evaluated["median_heap_delta_mb"] / evaluated["baseline_heap_delta_mb"]
        )

        evaluated["baseline_elapsed_pass"] = evaluated["elapsed_ratio"].isna() | (
            evaluated["elapsed_ratio"] <= elapsed_ratio_limit
        )

        evaluated["baseline_memory_pass"] = evaluated["memory_ratio"].isna() | (
            evaluated["memory_ratio"] <= memory_ratio_limit
        )

    else:
        evaluated["baseline_elapsed_s"] = np.nan
        evaluated["baseline_heap_delta_mb"] = np.nan
        evaluated["elapsed_ratio"] = np.nan
        evaluated["memory_ratio"] = np.nan
        evaluated["baseline_elapsed_pass"] = True
        evaluated["baseline_memory_pass"] = True

    checks = pd.concat(
        [
            _gp3_perf_check_rows(
                evaluated,
                "operation_completed",
                evaluated["operation_success"],
            ),
            _gp3_perf_check_rows(
                evaluated,
                "elapsed_absolute_limit",
                evaluated["elapsed_limit_pass"],
            ),
            _gp3_perf_check_rows(
                evaluated,
                "memory_absolute_limit",
                evaluated["memory_limit_pass"],
            ),
            _gp3_perf_check_rows(
                evaluated,
                "scaling_exponent_limit",
                evaluated["scaling_limit_pass"],
            ),
            _gp3_perf_check_rows(
                evaluated,
                "elapsed_baseline_ratio",
                evaluated["baseline_elapsed_pass"],
            ),
            _gp3_perf_check_rows(
                evaluated,
                "memory_baseline_ratio",
                evaluated["baseline_memory_pass"],
            ),
        ],
        ignore_index=True,
    )

    n_pass = int(checks["status"].eq("pass").sum())

    n_fail = int(checks["status"].eq("fail").sum())

    overall = pd.DataFrame(
        {
            "pass": [n_fail == 0],
            "n_checks": [int(len(checks))],
            "n_pass": [n_pass],
            "n_fail": [n_fail],
        }
    )

    return {
        "overall": overall,
        "checks": checks,
        "evaluated": evaluated,
        "limits": limits,
        "baseline_used": baseline_used,
        "elapsed_ratio_limit": elapsed_ratio_limit,
        "memory_ratio_limit": memory_ratio_limit,
    }


def write_gazepoint_performance_benchmark(
    data=None,
    path="performance_benchmark.csv",
    *,
    x=None,
    output_dir=None,
    prefix="gp3tools-performance",
):
    """Write performance benchmark output.

    Benchmark dictionaries use the R v2.3.0 four-file export contract.
    Plain DataFrames retain the original Python single-file interface.
    """
    if x is not None or output_dir is not None:
        if x is None or output_dir is None:
            raise ValueError("x and output_dir must be supplied together")

        if data is not None:
            raise TypeError("data cannot be combined with the R-compatible x/output_dir interface")

        if not isinstance(x, dict):
            raise TypeError("x must be a benchmark dictionary")

        regression = x.get(
            "regression",
            {},
        )

        if not isinstance(regression, dict):
            raise TypeError("x['regression'] must be a dictionary")

        required = {
            "trials": x.get("trials"),
            "summary": x.get("summary"),
            "checks": regression.get("checks"),
            "evaluated": regression.get("evaluated"),
        }

        missing = [name for name, value in required.items() if value is None]

        if missing:
            raise ValueError("benchmark object is missing: " + ", ".join(missing))

        root = Path(output_dir)
        root.mkdir(
            parents=True,
            exist_ok=True,
        )

        if not isinstance(prefix, str) or not prefix.strip():
            raise ValueError("prefix must be a non-empty string")

        files = {
            "trials": root / f"{prefix}-trials.csv",
            "summary": root / f"{prefix}-summary.csv",
            "checks": root / f"{prefix}-checks.csv",
            "evaluated": root / f"{prefix}-evaluated.csv",
        }

        for name, file in files.items():
            ensure_dataframe(
                required[name],
                copy=False,
            ).to_csv(
                file,
                index=False,
            )

        return {name: file.resolve() for name, file in files.items()}

    if data is None:
        raise TypeError("data is required for the Python interface")

    p = Path(path)
    p.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    ensure_dataframe(data).to_csv(
        p,
        index=False,
    )

    return p


def run_gazepoint_workflow(
    data=None,
    export_dir=None,
    output_dir=None,
    pattern=r"\.csv$",
    create_report=True,
    save_plots=False,
    **kwargs,
) -> dict[str, Any]:
    from .io import read_gazepoint_folder
    from .pupil import preprocess_gazepoint_signals
    from .qc import (
        audit_gazepoint_master,
        check_sampling_rate,
        create_gazepoint_master,
        summarise_tracking_quality,
    )

    if data is None:
        if export_dir is None:
            raise ValueError("Provide `data` or `export_dir`")
        data = read_gazepoint_folder(export_dir, pattern=pattern)
    master = create_gazepoint_master(data)
    results = {"master": master, "audit": audit_gazepoint_master(master)}
    try:
        results["sampling_rate"] = check_sampling_rate(master)
    except Exception as exc:
        results["sampling_rate_error"] = str(exc)
    try:
        results["tracking_quality"] = summarise_tracking_quality(master)
    except Exception as exc:
        results["tracking_quality_error"] = str(exc)
    try:
        results["preprocessed"] = preprocess_gazepoint_signals(master)
    except Exception as exc:
        results["preprocessing_error"] = str(exc)
    if output_dir:
        flat = {k: v for k, v in results.items() if isinstance(v, pd.DataFrame)}
        write_gazepoint_outputs(flat, output_dir)
        if create_report:
            results["report_path"] = str(
                create_gazepoint_report(
                    {**flat, **{f"audit_{k}": v for k, v in results.get("audit", {}).items()}},
                    Path(output_dir) / "gp3tools_report.html",
                )
            )
    return results


def summarise_gazepoint_workflow(result) -> pd.DataFrame:
    if not isinstance(result, dict):
        return pd.DataFrame({"component": ["result"], "status": ["available"]})
    return pd.DataFrame(
        {
            "component": list(result),
            "status": ["error" if str(k).endswith("_error") else "available" for k in result],
        }
    )


def create_gazepoint_cross_package_report(
    result, output_file="cross_package_report.html", **kwargs
):
    return create_gazepoint_report(
        result, output_file, title="gp3tools cross-package report", **kwargs
    )


def export_gazepoint_cluster_results(
    result,
    output_dir="cluster_results",
    prefix="cluster",
    *,
    overwrite=False,
):
    root = Path(output_dir)
    if root.exists() and any(root.iterdir()) and not overwrite:
        # Preserve the historical API when its default output_dir/prefix path is used.
        # R-compatible callers can set overwrite=True to reuse a populated directory.
        raise FileExistsError("output directory already exists; use overwrite=True to reuse it")
    root.mkdir(parents=True, exist_ok=True)

    if isinstance(result, dict) and any(
        key in result
        for key in (
            "cluster_summary",
            "cluster_table",
            "null_distribution",
            "null_statistics",
            "max_cluster_statistics",
            "permutation_distribution",
            "cluster_status",
        )
    ):
        from .stats import report_gazepoint_cluster_permutation, summarize_gazepoint_time_clusters

        try:
            clusters = summarize_gazepoint_time_clusters(result)
        except Exception:
            clusters = None
            for key in ("clusters", "cluster_summary", "cluster_table"):
                if key in result and result[key] is not None:
                    clusters = result[key]
                    break
        written_rows = []
        if isinstance(clusters, pd.DataFrame):
            path = root / "cluster_summary.csv"
            clusters.to_csv(path, index=False)
            written_rows.append({"file": str(path), "file_type": "cluster_summary"})
        null_values = next(
            (
                result[key]
                for key in [
                    "null_distribution",
                    "null_statistics",
                    "max_cluster_statistics",
                    "permutation_distribution",
                ]
                if key in result and np.asarray(result[key]).ndim == 1
            ),
            None,
        )
        if null_values is not None:
            path = root / "null_distribution.csv"
            pd.DataFrame({"null_statistic": np.asarray(null_values, dtype=float)}).to_csv(
                path, index=False
            )
            written_rows.append({"file": str(path), "file_type": "null_distribution"})
        try:
            report = report_gazepoint_cluster_permutation(result)
            report_text = (
                report.get("report_text", str(report)) if isinstance(report, dict) else str(report)
            )
            path = root / "cluster_report.txt"
            path.write_text(report_text, encoding="utf-8")
            written_rows.append({"file": str(path), "file_type": "report_text"})
        except Exception:
            pass
        if "settings" in result:
            settings = result["settings"]
            settings_frame = (
                pd.DataFrame([settings])
                if isinstance(settings, dict)
                else ensure_dataframe(settings)
            )
            path = root / "cluster_settings.csv"
            settings_frame.to_csv(path, index=False)
            written_rows.append({"file": str(path), "file_type": "settings"})
        if written_rows:
            return pd.DataFrame(written_rows)

    if isinstance(result, dict):
        return write_gazepoint_outputs(result, root, prefix=prefix)
    return export_gazepoint_tables({"clusters": ensure_dataframe(result)}, root, prefix=prefix)


def launch_gazepoint_qc_dashboard(data=None, **kwargs):
    """Create a lightweight Shiny-for-Python QC app when the optional dependency exists."""
    try:
        from shiny import App, render, ui
    except Exception as exc:
        return {
            "status": "optional-backend-unavailable",
            "backend": "shiny",
            "error": str(exc),
            "hint": "Install gp3tools[dashboard]",
        }
    df = ensure_dataframe(data) if data is not None else pd.DataFrame()
    app_ui = ui.page_fluid(ui.h2("gp3tools QC dashboard"), ui.output_text_verbatim("summary"))

    def server(input, output, session):
        @output
        @render.text
        def summary():
            return f"Rows: {len(df):,}\nColumns: {df.shape[1]}\nMissing cells: {int(df.isna().sum().sum()):,}"

    return App(app_ui, server)


# BEGIN R V2.3.0 CALL-SURFACE ALIASES
export_gazepoint_cluster_results = r_aliases(export_gazepoint_cluster_results, outdir="output_dir")
report_gazepoint_multiverse = r_aliases(report_gazepoint_multiverse, multiverse_results="data")
report_gazepoint_qc_overview = r_aliases(report_gazepoint_qc_overview, qc_bundle="data")
summarise_gazepoint_workflow = r_aliases(summarise_gazepoint_workflow, results="result")
# END R V2.3.0 CALL-SURFACE ALIASES
